name: Build Linux Kernel

on: [push]

jobs:
  build_samples:
    name: build_samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get crosstool chains
        uses: suda-morris/crosstool_ng_action@master
        with:
          WORK_DIR: arm9-linux-gnueabi
          ARCH: arm9
      - name: Build Linux Kernel
        run: |
          git submodule update --init --recursive
          sudo apt-get install bison flex texinfo help2man libssl-dev libncurses5-dev python-dev
          export PATH="${GITHUB_WORKSPACE}/arm9-linux-gnueabi/x-tools/bin":$PATH
          export ARCH=arm
          export CROSS_COMPILE=arm-unknown-linux-gnueabi-
          cd kernel/linux-5.2
          ls -lash
          make licheepi_nano_defconfig
          make -j4
      - name: Upload Kernel Image
        uses: actions/upload-artifact@master
        with:
          name: zImage-artifact
          path: kernel/linux-5.2/arch/arm/boot

